language: node_js

node_js:
   - node

before_script:
  - npm install -g --silent @angular/cli

script:
   - ng lint
     # At some point figure out setting up karma and travis.

notifications:
    on_failure: change
    on_success: change
