language: node_js
node_js:
   - node
dist: trusty
sudo: required
services:
     - docker
addons:
    chrome: stable
cache:
    npm: true
    directories:
        - node_modules
before_script:
     - bash ./scripts/setup_api.sh
     - npm install -g --silent @angular/cli

script:
   - ng test --no-progress
