language: node_js
node_js:
   - node
dist: trusty
sudo: required
services:
     - docker
addons:
    chrome: stable
cache:
    npm: true
    directories:
        - node_modules
before_script:
	- docker swarm init
	- docker service create --name registry --publish published=5000,target=5000 registry:2
	- docker build -t 127.0.0.1:5000/docks-ui:local .
	- docker push 127.0.0.1:5000/docks-ui:local
	- docker stack deploy -c docker-compose-api.yml docks-api
	- npm install -g --silent @angular/cli

script:
   - ng test --no-progress
