language: node_js
node_js:
   - node
dist: trusty
sudo: required
services:
     - docker
addons:
    chrome: stable
cache:
    npm: true
    directories:
        - node_modules
before_script:
     - bash ./write-api-address.sh
     - docker swarm init
     - docker stack deploy -c docker-compose-api.yml docks-api
     - npm install -g --silent @angular/cli

script:
   - ng test --no-progress
