version: '3.2'

services:
  angular:
    image: 127.0.0.1:5000/docks-angular-demo
    build:
      context: ../
      dockerfile: Dockerfile-dev
    volumes:
      - type: bind
        source: ../
        target: /app
    ports:
      - "4200:4200"

  docks-api:
    image: tripleparity/docks-api:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080